// Stammdaten: Supermarkt-Kategorien, Zutatenkatalog, Standard-Rezepte und Voreinstellungen.
// Zutaten in Rezepten werden als Text geschrieben ("120 g Rote Linsen") und von app.js geparst.

const KATEGORIEN = [
  "Obst & Gemüse",
  "Brot & Backwaren",
  "Kühlregal",
  "Tiefkühl",
  "Konserven",
  "Nudeln, Reis & Getreide",
  "Hülsenfrüchte",
  "Gewürze, Öle & Saucen",
  "Nüsse & Saaten",
  "Sonstiges",
];

// name: [Kategorie, Grundvorrat?]  – Grundvorrat-Artikel gelten anfangs als "genug da".
const KATALOG = {
  "Hokkaido-Kürbis": ["Obst & Gemüse", false],
  "Kartoffeln": ["Obst & Gemüse", false],
  "Karotten": ["Obst & Gemüse", false],
  "Paprika": ["Obst & Gemüse", false],
  "Gurke": ["Obst & Gemüse", false],
  "Lauch": ["Obst & Gemüse", false],
  "Zwiebeln": ["Obst & Gemüse", true],
  "Knoblauch": ["Obst & Gemüse", true],
  "Brokkoli": ["Obst & Gemüse", false],
  "Zitrone": ["Obst & Gemüse", false],
  "Champignons": ["Obst & Gemüse", false],
  "Weißkohl": ["Obst & Gemüse", false],
  "Spitzkohl": ["Obst & Gemüse", false],
  "Rotkohl": ["Obst & Gemüse", false],
  "Kopfsalat": ["Obst & Gemüse", false],
  "Frühlingszwiebeln": ["Obst & Gemüse", false],
  "Ingwer": ["Obst & Gemüse", false],
  "Zucchini": ["Obst & Gemüse", false],
  "Äpfel": ["Obst & Gemüse", false],
  "Bananen": ["Obst & Gemüse", false],

  "Vollkornbrot": ["Brot & Backwaren", false],
  "Vollkornwraps": ["Brot & Backwaren", false],
  "Fladenbrot": ["Brot & Backwaren", false],
  "Vollkornbrötchen": ["Brot & Backwaren", false],

  "Eier": ["Kühlregal", false],
  "Magerquark": ["Kühlregal", false],
  "Skyr": ["Kühlregal", false],
  "Naturjoghurt": ["Kühlregal", false],
  "Milch": ["Kühlregal", false],
  "Hüttenkäse": ["Kühlregal", false],
  "Feta": ["Kühlregal", false],
  "Mozzarella": ["Kühlregal", false],
  "Geriebener Käse": ["Kühlregal", false],
  "Parmesan": ["Kühlregal", true],
  "Tofu natur": ["Kühlregal", false],
  "Räuchertofu": ["Kühlregal", false],

  "TK-Gemüsemischung": ["Tiefkühl", false],
  "TK-Blattspinat": ["Tiefkühl", false],
  "TK-Erbsen": ["Tiefkühl", false],
  "TK-Beeren": ["Tiefkühl", true],
  "TK-Kräuter": ["Tiefkühl", true],

  "Passierte Tomaten": ["Konserven", false],
  "Stückige Tomaten": ["Konserven", false],
  "Kichererbsen": ["Konserven", false],
  "Kidneybohnen": ["Konserven", false],
  "Mais": ["Konserven", false],
  "Weiße Bohnen": ["Konserven", false],
  "Kokosmilch": ["Konserven", false],

  "Vollkornspaghetti": ["Nudeln, Reis & Getreide", true],
  "Vollkornpenne": ["Nudeln, Reis & Getreide", true],
  "Reis": ["Nudeln, Reis & Getreide", true],
  "Couscous": ["Nudeln, Reis & Getreide", true],
  "Haferflocken": ["Nudeln, Reis & Getreide", true],
  "Vollkornmehl": ["Nudeln, Reis & Getreide", true],

  "Rote Linsen": ["Hülsenfrüchte", true],
  "Tellerlinsen": ["Hülsenfrüchte", true],

  "Rapsöl": ["Gewürze, Öle & Saucen", true],
  "Olivenöl": ["Gewürze, Öle & Saucen", true],
  "Gemüsebrühe": ["Gewürze, Öle & Saucen", true],
  "Salz": ["Gewürze, Öle & Saucen", true],
  "Pfeffer": ["Gewürze, Öle & Saucen", true],
  "Paprikapulver": ["Gewürze, Öle & Saucen", true],
  "Kreuzkümmel": ["Gewürze, Öle & Saucen", true],
  "Currypulver": ["Gewürze, Öle & Saucen", true],
  "Italienische Kräuter": ["Gewürze, Öle & Saucen", true],
  "Chiliflocken": ["Gewürze, Öle & Saucen", true],
  "Kümmel": ["Gewürze, Öle & Saucen", true],
  "Tomatenmark": ["Gewürze, Öle & Saucen", true],
  "Sojasauce": ["Gewürze, Öle & Saucen", true],
  "Erdnussbutter": ["Gewürze, Öle & Saucen", true],
  "Senf": ["Gewürze, Öle & Saucen", true],
  "Honig": ["Gewürze, Öle & Saucen", true],
  "Essig": ["Gewürze, Öle & Saucen", true],

  "Walnüsse": ["Nüsse & Saaten", true],
  "Leinsamen": ["Nüsse & Saaten", true],
};

// Nährwerte je 100 g als [kcal, Eiweiß, Kohlenhydrate, Fett, Ballaststoffe] – Richtwerte.
// Nudeln, Reis, Linsen, Couscous roh; Konserven abgetropft. Optional: Gramm je Einheit (Stk, Dose, …).
const NAEHRWERTE = {
  "Hokkaido-Kürbis": { n: [63, 1.7, 12.6, 0.6, 2.5], Stk: 1000 },
  "Kartoffeln": { n: [72, 2, 15.6, 0.1, 2.1], Stk: 100 },
  "Karotten": { n: [36, 1, 7, 0.2, 3.6], Stk: 100 },
  "Paprika": { n: [30, 1, 5.5, 0.3, 3.5], Stk: 160 },
  "Gurke": { n: [13, 0.6, 1.8, 0.2, 0.5], Stk: 400 },
  "Lauch": { n: [29, 2.2, 3.3, 0.3, 2.3], Stk: 200 },
  "Zwiebeln": { n: [33, 1.2, 6, 0.3, 1.8], Stk: 80 },
  "Knoblauch": { n: [140, 6, 28, 0.1, 2], Stk: 40, Zehe: 4 },
  "Brokkoli": { n: [35, 3.8, 2.7, 0.2, 3], Stk: 400 },
  "Zitrone": { n: [36, 0.7, 3.2, 0.6, 0.3], Stk: 100 },
  "Champignons": { n: [22, 3, 0.6, 0.3, 2] },
  "Weißkohl": { n: [30, 1.4, 4.2, 0.2, 3], Stk: 1200 },
  "Spitzkohl": { n: [28, 1.5, 4, 0.3, 2.5], Stk: 800 },
  "Rotkohl": { n: [29, 1.5, 3.5, 0.2, 2.5], Stk: 800 },
  "Kopfsalat": { n: [14, 1.2, 1.1, 0.2, 1.4], Stk: 300 },
  "Frühlingszwiebeln": { n: [30, 1.8, 4.7, 0.2, 2.5], Bund: 120 },
  "Ingwer": { n: [80, 1.8, 15, 0.8, 2] },
  "Zucchini": { n: [19, 1.6, 2.1, 0.4, 1.1], Stk: 250 },
  "Äpfel": { n: [54, 0.3, 11.4, 0.4, 2], Stk: 150 },
  "Bananen": { n: [93, 1.1, 20, 0.2, 1.8], Stk: 120 },

  "Vollkornbrot": { n: [220, 7, 39, 1.2, 8], Stk: 750, Scheibe: 50 },
  "Vollkornwraps": { n: [300, 9, 48, 7, 6], Stk: 62 },
  "Fladenbrot": { n: [250, 8.5, 50, 1.5, 2.5], Stk: 400 },
  "Vollkornbrötchen": { n: [240, 9, 42, 2.5, 6], Stk: 70 },

  "Eier": { n: [137, 12.9, 0.7, 9.3, 0], Stk: 55 },
  "Magerquark": { n: [67, 12, 4, 0.3, 0] },
  "Skyr": { n: [63, 11, 4, 0.2, 0] },
  "Naturjoghurt": { n: [66, 3.8, 4.7, 3.5, 0] },
  "Milch": { n: [47, 3.4, 4.8, 1.5, 0] },
  "Hüttenkäse": { n: [98, 12.5, 2.6, 4.3, 0] },
  "Feta": { n: [260, 17, 0.5, 21, 0] },
  "Mozzarella": { n: [240, 18, 1, 18, 0], Kugel: 125 },
  "Geriebener Käse": { n: [360, 25, 0, 28, 0] },
  "Parmesan": { n: [390, 33, 0, 28, 0] },
  "Tofu natur": { n: [125, 13, 1.5, 7.5, 0.5] },
  "Räuchertofu": { n: [150, 16, 1.5, 9, 0.5] },

  "TK-Gemüsemischung": { n: [40, 2, 6, 0.4, 3] },
  "TK-Blattspinat": { n: [20, 2.5, 0.6, 0.4, 2] },
  "TK-Erbsen": { n: [80, 6, 11, 0.5, 5] },
  "TK-Beeren": { n: [45, 1, 8, 0.4, 4] },
  "TK-Kräuter": { n: [40, 3, 5, 0.6, 4], EL: 5 },

  "Passierte Tomaten": { n: [32, 1.4, 5, 0.2, 1.3] },
  "Stückige Tomaten": { n: [22, 1.2, 3.5, 0.2, 1], Dose: 400 },
  "Kichererbsen": { n: [120, 7, 15, 2.5, 6], Dose: 240 },
  "Kidneybohnen": { n: [105, 7.5, 14, 0.6, 7], Dose: 250 },
  "Mais": { n: [80, 2.8, 14, 1.2, 2.8], Dose: 285 },
  "Weiße Bohnen": { n: [95, 7, 13, 0.5, 6], Dose: 250 },
  "Kokosmilch": { n: [180, 1.5, 3, 18, 0], Dose: 400 },

  "Vollkornspaghetti": { n: [350, 13, 64, 2.5, 8] },
  "Vollkornpenne": { n: [350, 13, 64, 2.5, 8] },
  "Reis": { n: [350, 8, 75, 1.5, 2] },
  "Couscous": { n: [355, 12, 72, 1.9, 5] },
  "Haferflocken": { n: [370, 13.5, 59, 7, 10] },
  "Vollkornmehl": { n: [330, 12, 60, 2, 10] },

  "Rote Linsen": { n: [340, 24, 50, 1.5, 11] },
  "Tellerlinsen": { n: [330, 24, 48, 1.5, 11] },

  "Rapsöl": { n: [900, 0, 0, 100, 0] },
  "Olivenöl": { n: [900, 0, 0, 100, 0] },
  "Gemüsebrühe": { n: [200, 8, 25, 7, 0], TL: 5 },
  "Salz": { n: [0, 0, 0, 0, 0] },
  "Pfeffer": { n: [250, 10, 40, 3, 25], TL: 2 },
  "Paprikapulver": { n: [300, 14, 20, 13, 35], TL: 2.5 },
  "Kreuzkümmel": { n: [375, 18, 34, 22, 10], TL: 2 },
  "Currypulver": { n: [325, 14, 25, 14, 33], TL: 2.5 },
  "Italienische Kräuter": { n: [270, 10, 40, 5, 30], TL: 1 },
  "Chiliflocken": { n: [320, 12, 50, 14, 27] },
  "Kümmel": { n: [330, 20, 12, 15, 38], TL: 2 },
  "Tomatenmark": { n: [85, 4.5, 13, 0.5, 3], EL: 15 },
  "Sojasauce": { n: [60, 8, 6, 0.5, 0], EL: 15 },
  "Erdnussbutter": { n: [600, 25, 13, 50, 7], EL: 16 },
  "Senf": { n: [90, 6, 5, 5, 2], TL: 5 },
  "Honig": { n: [305, 0.4, 76, 0, 0], TL: 7 },
  "Essig": { n: [20, 0, 1, 0, 0], EL: 15 },

  "Walnüsse": { n: [680, 15, 11, 65, 6] },
  "Leinsamen": { n: [490, 24, 2, 37, 26] },
};

// Typische Haltbarkeit in Tagen: [ab Einkauf (ungeöffnet, richtig gelagert), nach dem Öffnen/Anschneiden].
// Nur Verderbliches und Konserven – ohne Eintrag gilt eine Zutat als lange haltbar.
const HALTBARKEIT = {
  "Hokkaido-Kürbis": [30, 5], "Kartoffeln": [21], "Karotten": [14], "Paprika": [7], "Gurke": [7, 2],
  "Lauch": [7, 4], "Brokkoli": [4], "Zitrone": [14, 4], "Champignons": [3], "Weißkohl": [21, 7],
  "Spitzkohl": [10, 5], "Rotkohl": [21, 7], "Kopfsalat": [4, 2], "Frühlingszwiebeln": [5], "Ingwer": [21, 14],
  "Zucchini": [7, 3], "Äpfel": [21], "Bananen": [6],
  "Vollkornbrot": [5], "Vollkornwraps": [14, 5], "Fladenbrot": [2], "Vollkornbrötchen": [2],
  "Eier": [21], "Magerquark": [14, 3], "Skyr": [14, 3], "Naturjoghurt": [14, 4], "Milch": [7, 3],
  "Hüttenkäse": [10, 3], "Feta": [30, 5], "Mozzarella": [14, 2], "Geriebener Käse": [21, 5],
  "Parmesan": [60, 21], "Tofu natur": [21, 4], "Räuchertofu": [21, 5],
  "Passierte Tomaten": [365, 4], "Stückige Tomaten": [365, 3], "Kichererbsen": [365, 3],
  "Kidneybohnen": [365, 3], "Mais": [365, 3], "Weiße Bohnen": [365, 3], "Kokosmilch": [365, 3],
};

// Übliche Packungsgrößen [Menge, Einheit] – damit die Einkaufsliste ganze Packungen nennt
// und die App weiß, was nach dem Kochen übrig bleibt.
const PACKUNGEN = {
  "Feta": [200, "g"], "Champignons": [250, "g"], "Magerquark": [500, "g"], "Skyr": [500, "g"],
  "Naturjoghurt": [500, "g"], "Hüttenkäse": [200, "g"], "Tofu natur": [200, "g"], "Räuchertofu": [200, "g"],
  "Geriebener Käse": [200, "g"], "Passierte Tomaten": [500, "g"], "TK-Blattspinat": [450, "g"],
  "TK-Erbsen": [450, "g"], "TK-Gemüsemischung": [750, "g"], "Milch": [1000, "ml"], "Vollkornwraps": [6, "Stk"],
};

// Gramm je Einheit, falls bei der Zutat nichts anderes steht
const EINHEIT_GRAMM = {
  g: 1, ml: 1, EL: 10, TL: 4, Prise: 0.3, Zehe: 4, Scheibe: 50, Bund: 100,
  Kugel: 125, Dose: 400, Stk: 100, Packung: 250, Glas: 350, Becher: 500,
};

const STANDARD_REZEPTE = [
  {
    id: "linsen-bolognese", name: "Linsen-Bolognese", minuten: 25, portionen: 2,
    tags: ["Pasta", "Sport"],
    zutaten: ["1 Zwiebeln", "2 Zehe Knoblauch", "200 g Karotten", "1 EL Olivenöl", "1 EL Tomatenmark",
      "120 g Rote Linsen", "500 g Passierte Tomaten", "1 TL Italienische Kräuter", "Beilage: Vollkornspaghetti", "30 g Parmesan"],
    schritte: ["Zwiebel und Knoblauch hacken, Karotten fein reiben, alles in Öl anbraten.",
      "Tomatenmark kurz mitrösten, Linsen, passierte Tomaten und 200 ml Wasser dazugeben.",
      "15 Min köcheln lassen, mit Kräutern, Salz und Pfeffer abschmecken.",
      "Spaghetti kochen, mit der Sauce anrichten und Parmesan drüberreiben."],
  },
  {
    id: "ofengemuese", name: "Ofengemüse mit Kichererbsen und Feta", minuten: 40, portionen: 2,
    tags: ["Ofen"],
    zutaten: ["½ Hokkaido-Kürbis", "500 g Kartoffeln", "200 g Karotten", "1 Dose Kichererbsen", "2 EL Rapsöl",
      "1 TL Paprikapulver", "150 g Feta", "250 g Magerquark", "1 EL TK-Kräuter"],
    schritte: ["Ofen auf 200 °C vorheizen.",
      "Kürbis, Kartoffeln und Karotten würfeln, Kichererbsen abgießen.",
      "Alles mit Öl, Paprikapulver und Salz mischen, 30 Min backen.",
      "Feta drüberbröseln, Quark mit Kräutern, Salz und etwas Wasser glatt rühren und dazu servieren."],
  },
  {
    id: "shakshuka", name: "Shakshuka mit Feta", minuten: 25, portionen: 2,
    tags: ["Pfanne", "Eier"],
    zutaten: ["1 Zwiebeln", "1 Paprika", "1 EL Rapsöl", "1 Dose Stückige Tomaten", "1 TL Kreuzkümmel",
      "1 TL Paprikapulver", "4 Eier", "100 g Feta"],
    schritte: ["Zwiebel und Paprika würfeln und in Öl anbraten.",
      "Tomaten und Gewürze dazu, 5 Min köcheln.",
      "Mulden in die Sauce drücken, Eier hineinschlagen, Deckel drauf und 6–8 Min stocken lassen.",
      "Feta drüberbröseln. Dazu Vollkornbrot."],
  },
  {
    id: "couscous-salat", name: "Couscous-Salat mit Kichererbsen", minuten: 15, portionen: 2,
    tags: ["Schnell", "Kalt"],
    zutaten: ["Beilage: Couscous", "1 TL Gemüsebrühe", "1 Dose Kichererbsen", "½ Gurke", "100 g Feta",
      "1 Zitrone", "2 EL Olivenöl", "1 EL TK-Kräuter"],
    schritte: ["Couscous mit etwas mehr heißer Brühe übergießen (ca. 1,25-fache Menge), 5 Min quellen lassen.",
      "Gurke würfeln, Kichererbsen abgießen, Feta zerbröseln.",
      "Alles mit Zitronensaft, Öl und Kräutern mischen, abschmecken. Schmeckt auch kalt am nächsten Tag."],
  },
  {
    id: "tofu-pfanne", name: "Tofu-Gemüsepfanne mit Erdnusssauce", minuten: 20, portionen: 2,
    tags: ["Pfanne", "Reis", "Sport"],
    zutaten: ["400 g Tofu natur", "1 EL Rapsöl", "750 g TK-Gemüsemischung", "2 EL Erdnussbutter",
      "3 EL Sojasauce", "1 Zehe Knoblauch", "Beilage: Reis"],
    schritte: ["Reis kochen.",
      "Tofu würfeln und in Öl knusprig braten.",
      "TK-Gemüse dazugeben und mitbraten, bis es gar ist.",
      "Erdnussbutter, Sojasauce, gepressten Knoblauch und etwas Wasser verrühren und unterrühren."],
  },
  {
    id: "bohnen-wraps", name: "Bohnen-Wraps mit Joghurt-Dip", minuten: 15, portionen: 2,
    tags: ["Schnell", "Pfanne"],
    zutaten: ["1 Dose Kidneybohnen", "1 Dose Mais", "1 Paprika", "1 EL Rapsöl", "1 TL Kreuzkümmel",
      "4 Stk Vollkornwraps", "100 g Geriebener Käse", "150 g Naturjoghurt", "1 Zehe Knoblauch", "1 EL TK-Kräuter"],
    schritte: ["Paprika würfeln, mit Bohnen, Mais und Kreuzkümmel kurz anbraten.",
      "Joghurt mit Knoblauch, Kräutern und Salz verrühren.",
      "Wraps kurz erwärmen, mit Füllung und Käse belegen, einrollen, Dip dazu."],
  },
  {
    id: "linsen-kokos-curry", name: "Rotes Linsen-Kokos-Curry mit Spinat", minuten: 25, portionen: 2,
    tags: ["Curry", "Reis", "Sport"],
    zutaten: ["1 Zwiebeln", "1 EL Rapsöl", "2 TL Currypulver", "150 g Rote Linsen", "1 Dose Kokosmilch",
      "1 Dose Stückige Tomaten", "225 g TK-Blattspinat", "Beilage: Reis"],
    schritte: ["Reis kochen.",
      "Zwiebel würfeln und in Öl anbraten, Currypulver kurz mitrösten.",
      "Linsen, Kokosmilch, Tomaten und 200 ml Wasser dazu, 15 Min köcheln.",
      "Spinat unterrühren, bis er heiß ist, abschmecken."],
  },
  {
    id: "kartoffel-linsen-suppe", name: "Kartoffel-Karotten-Linsen-Suppe", minuten: 30, portionen: 2,
    tags: ["Suppe"],
    zutaten: ["1 Zwiebeln", "1 Stk Lauch", "1 EL Rapsöl", "500 g Kartoffeln", "300 g Karotten",
      "80 g Rote Linsen", "2 TL Gemüsebrühe", "200 g Hüttenkäse"],
    schritte: ["Zwiebel und Lauch schneiden und in Öl anbraten.",
      "Kartoffeln und Karotten würfeln, mit Linsen und 1 l Brühe dazu, 20 Min kochen.",
      "Pürieren und abschmecken. Dazu Brot mit Hüttenkäse."],
  },
  {
    id: "chili-sin-carne", name: "Chili sin Carne", minuten: 25, portionen: 3,
    tags: ["Reis", "Sport"],
    zutaten: ["1 Zwiebeln", "1 Paprika", "1 EL Rapsöl", "1 TL Paprikapulver", "1 TL Kreuzkümmel",
      "1 Prise Chiliflocken", "2 Dose Stückige Tomaten", "2 Dose Kidneybohnen", "1 Dose Mais",
      "80 g Rote Linsen", "Beilage: Reis"],
    schritte: ["Reis kochen.",
      "Zwiebel und Paprika würfeln und in Öl anbraten, Gewürze kurz mitrösten.",
      "Tomaten, abgespülte Bohnen, Mais, Linsen und 200 ml Wasser dazu, 20 Min köcheln.",
      "Abschmecken und mit Reis servieren."],
  },
  {
    id: "pasta-brokkoli-feta", name: "Vollkornpasta mit Brokkoli, Erbsen und Feta", minuten: 20, portionen: 2,
    tags: ["Pasta", "Schnell", "Sport"],
    zutaten: ["Beilage: Vollkornpenne", "1 Stk Brokkoli", "150 g TK-Erbsen", "150 g Feta", "1 Zitrone",
      "1 Zehe Knoblauch", "1 EL Olivenöl"],
    schritte: ["Nudeln kochen, in den letzten 5 Min Brokkoli-Röschen und Erbsen mitkochen.",
      "Eine Tasse Nudelwasser abnehmen, dann abgießen.",
      "Mit zerbröseltem Feta, Zitronensaft, gepresstem Knoblauch, Öl und etwas Nudelwasser mischen."],
  },
  {
    id: "frittata", name: "Kartoffel-Spinat-Frittata mit Salat", minuten: 25, portionen: 2,
    tags: ["Pfanne", "Eier"],
    zutaten: ["400 g Kartoffeln", "1 Zwiebeln", "1 EL Rapsöl", "225 g TK-Blattspinat", "6 Eier",
      "50 g Geriebener Käse", "½ Kopfsalat"],
    schritte: ["Kartoffeln kochen (oder Reste vom Vortag nehmen), in Scheiben schneiden.",
      "Mit Zwiebel in Öl anbraten, aufgetauten Spinat dazugeben.",
      "Eier mit Käse, Salz und Pfeffer verquirlen und drübergießen.",
      "Mit Deckel bei kleiner Hitze 10–12 Min stocken lassen. Dazu Salat. Schmeckt auch kalt."],
  },
  {
    id: "kichererbsen-curry", name: "Kichererbsen-Spinat-Curry", minuten: 20, portionen: 2,
    tags: ["Curry", "Reis", "Sport"],
    zutaten: ["1 Zwiebeln", "1 Zehe Knoblauch", "1 EL Rapsöl", "2 TL Currypulver", "2 Dose Kichererbsen",
      "1 Dose Kokosmilch", "1 Dose Stückige Tomaten", "225 g TK-Blattspinat", "Beilage: Reis"],
    schritte: ["Reis kochen.",
      "Zwiebel und Knoblauch in Öl anbraten, Currypulver kurz mitrösten.",
      "Kichererbsen, Kokosmilch und Tomaten dazu, 10 Min köcheln.",
      "Spinat unterrühren und abschmecken."],
  },
  {
    id: "wrap-pizza", name: "Wrap-Pizza", minuten: 15, portionen: 2,
    tags: ["Ofen", "Schnell"],
    zutaten: ["4 Stk Vollkornwraps", "250 g Passierte Tomaten", "1 TL Italienische Kräuter", "1 Paprika",
      "250 g Champignons", "2 Kugel Mozzarella"],
    schritte: ["Ofen auf 220 °C vorheizen.",
      "Passierte Tomaten mit Kräutern und Salz würzen, auf die Wraps streichen.",
      "Mit Paprika, Champignons und Mozzarella belegen.",
      "8–10 Min backen."],
  },
  {
    id: "linsen-eintopf", name: "Gemüse-Linsen-Eintopf mit Weißkohl", minuten: 35, portionen: 2,
    tags: ["Suppe"],
    zutaten: ["1 Zwiebeln", "1 EL Rapsöl", "¼ Weißkohl", "300 g Karotten", "400 g Kartoffeln",
      "120 g Tellerlinsen", "2 TL Gemüsebrühe", "1 TL Senf", "1 EL Essig"],
    schritte: ["Zwiebel in Öl anbraten.",
      "Kohl in Streifen, Karotten und Kartoffeln in Würfel schneiden, mit Linsen und 1,2 l Brühe dazu.",
      "30 Min köcheln lassen.",
      "Mit Senf, Essig, Salz und Pfeffer abschmecken."],
  },
  {
    id: "gefuellte-paprika", name: "Gefüllte Paprika mit Couscous", minuten: 40, portionen: 2,
    tags: ["Ofen"],
    zutaten: ["100 g Couscous", "1 TL Gemüsebrühe", "1 Dose Kichererbsen", "100 g Feta", "1 EL Tomatenmark",
      "1 EL TK-Kräuter", "3 Paprika"],
    schritte: ["Ofen auf 200 °C vorheizen.",
      "Couscous mit 200 ml heißer Brühe übergießen, 5 Min quellen lassen.",
      "Mit Kichererbsen, zerbröseltem Feta, Tomatenmark und Kräutern mischen.",
      "Paprika halbieren, entkernen, füllen und 25 Min backen."],
  },
  {
    id: "erdnuss-nudeln", name: "Erdnuss-Nudeln mit Tofu", minuten: 20, portionen: 2,
    tags: ["Pasta", "Pfanne", "Sport"],
    zutaten: ["400 g Tofu natur", "1 EL Rapsöl", "1 Paprika", "150 g Karotten", "½ Bund Frühlingszwiebeln",
      "Beilage: Vollkornspaghetti", "2 EL Erdnussbutter", "3 EL Sojasauce", "1 Zehe Knoblauch"],
    schritte: ["Spaghetti kochen.",
      "Tofu würfeln und knusprig braten, Paprika, Karotten (in Streifen) und Frühlingszwiebeln kurz mitbraten.",
      "Erdnussbutter, Sojasauce, Knoblauch und etwas Nudelwasser verrühren.",
      "Nudeln und Sauce unterheben."],
  },
  {
    id: "ofenkartoffeln", name: "Ofenkartoffeln mit Kräuterquark und Spiegelei", minuten: 45, portionen: 2,
    tags: ["Ofen", "Eier"],
    zutaten: ["Beilage: Kartoffeln", "2 EL Rapsöl", "1 TL Paprikapulver", "1 Stk Brokkoli", "250 g Magerquark",
      "1 EL TK-Kräuter", "2 Eier"],
    schritte: ["Ofen auf 200 °C vorheizen.",
      "Kartoffeln in Spalten schneiden, mit Öl, Paprikapulver und Salz mischen, 35 Min backen.",
      "Brokkoli-Röschen die letzten 15 Min mit aufs Blech legen.",
      "Quark mit Kräutern anrühren, Spiegeleier braten, alles zusammen servieren."],
  },
  {
    id: "linsen-dal", name: "Linsen-Dal mit Spinat und Fladenbrot", minuten: 25, portionen: 2,
    tags: ["Curry"],
    zutaten: ["1 Zwiebeln", "2 Zehe Knoblauch", "10 g Ingwer", "1 EL Rapsöl", "2 TL Currypulver",
      "1 TL Kreuzkümmel", "150 g Rote Linsen", "1 Dose Stückige Tomaten", "225 g TK-Blattspinat", "1 Stk Fladenbrot"],
    schritte: ["Zwiebel, Knoblauch und Ingwer fein hacken und in Öl anbraten.",
      "Gewürze kurz mitrösten, Linsen, Tomaten und 500 ml Wasser dazu.",
      "15 Min köcheln, Spinat unterrühren, abschmecken.",
      "Mit Fladenbrot servieren."],
  },
  {
    id: "gebratener-reis", name: "Gebratener Reis mit Ei und Gemüse", minuten: 15, portionen: 2,
    tags: ["Reis", "Pfanne", "Schnell", "Eier"],
    zutaten: ["Beilage: Reis", "1 EL Rapsöl", "150 g TK-Erbsen", "150 g Karotten", "½ Bund Frühlingszwiebeln",
      "4 Eier", "2 EL Sojasauce"],
    schritte: ["Am besten Reis vom Vortag nehmen (sonst kochen und auskühlen lassen).",
      "Karotten würfeln, mit Erbsen und Frühlingszwiebeln in Öl anbraten.",
      "Reis dazu und knusprig braten.",
      "Eier verquirlen, unterrühren bis sie gestockt sind, mit Sojasauce würzen."],
  },
  {
    id: "bohnen-bratlinge", name: "Bohnen-Bratlinge mit Joghurt-Dip", minuten: 25, portionen: 2,
    tags: ["Pfanne"],
    zutaten: ["2 Dose Kidneybohnen", "80 g Haferflocken", "1 Eier", "1 Zwiebeln", "1 TL Kreuzkümmel",
      "1 TL Paprikapulver", "2 EL Rapsöl", "150 g Naturjoghurt", "1 Zehe Knoblauch", "½ Kopfsalat"],
    schritte: ["Bohnen abspülen und mit einer Gabel zerdrücken.",
      "Mit Haferflocken, Ei, fein gehackter Zwiebel und Gewürzen mischen, 5 Min ziehen lassen.",
      "Bratlinge formen und in Öl je Seite 4 Min braten.",
      "Joghurt mit Knoblauch und Salz verrühren, mit Salat servieren. Reste schmecken im Brötchen."],
  },
  {
    id: "kuerbis-linsen-suppe", name: "Kürbis-Linsen-Suppe mit Kokosmilch", minuten: 30, portionen: 3,
    tags: ["Suppe"],
    zutaten: ["1 Zwiebeln", "10 g Ingwer", "1 EL Rapsöl", "1 Hokkaido-Kürbis", "80 g Rote Linsen",
      "1 Dose Kokosmilch", "2 TL Gemüsebrühe", "1 TL Currypulver"],
    schritte: ["Zwiebel und Ingwer in Öl anbraten.",
      "Kürbis (Hokkaido mit Schale) würfeln, mit Linsen, Kokosmilch und 600 ml Brühe dazu.",
      "20 Min kochen, pürieren, mit Curry, Salz und Pfeffer abschmecken."],
  },
  {
    id: "nudelauflauf", name: "Vollkorn-Nudelauflauf mit Zucchini", minuten: 40, portionen: 2,
    tags: ["Ofen", "Pasta", "Sport"],
    zutaten: ["Beilage: Vollkornpenne", "1 Zwiebeln", "1 Zucchini", "1 Paprika", "500 g Passierte Tomaten",
      "1 TL Italienische Kräuter", "1 Kugel Mozzarella", "50 g Geriebener Käse"],
    schritte: ["Ofen auf 200 °C vorheizen, Nudeln knapp gar kochen.",
      "Zwiebel, Zucchini und Paprika würfeln, mit Nudeln, passierten Tomaten und Kräutern mischen.",
      "In eine Auflaufform geben, Mozzarella und Käse drauf.",
      "25 Min backen."],
  },
  {
    id: "mex-reispfanne", name: "Mexikanische Reispfanne", minuten: 20, portionen: 2,
    tags: ["Reis", "Pfanne", "Sport"],
    zutaten: ["1 Zwiebeln", "1 Paprika", "1 EL Rapsöl", "Beilage: Reis", "1 Dose Stückige Tomaten",
      "1 TL Gemüsebrühe", "1 TL Paprikapulver", "1 TL Kreuzkümmel", "1 Dose Kidneybohnen", "1 Dose Mais",
      "100 g Geriebener Käse"],
    schritte: ["Zwiebel und Paprika in Öl anbraten.",
      "Reis, Tomaten, Gewürze und gut doppelt so viel Brühe wie Reis dazu, mit Deckel 18 Min köcheln.",
      "Bohnen und Mais unterheben, Käse drüberstreuen und schmelzen lassen."],
  },
  {
    id: "kichererbsen-pfanne", name: "Kichererbsen-Gemüse-Pfanne mit Couscous", minuten: 20, portionen: 2,
    tags: ["Pfanne", "Schnell"],
    zutaten: ["1 Zucchini", "1 Paprika", "1 EL Olivenöl", "2 Dose Kichererbsen", "1 TL Kreuzkümmel",
      "1 Zehe Knoblauch", "Beilage: Couscous", "1 TL Gemüsebrühe", "150 g Naturjoghurt"],
    schritte: ["Couscous mit etwas mehr heißer Brühe übergießen (ca. 1,25-fache Menge) und quellen lassen.",
      "Zucchini und Paprika würfeln und in Öl anbraten.",
      "Kichererbsen, Knoblauch und Kreuzkümmel dazu, 5 Min mitbraten.",
      "Mit Couscous und Joghurt servieren."],
  },
  {
    id: "spinat-feta-pfannkuchen", name: "Herzhafte Pfannkuchen mit Spinat und Feta", minuten: 25, portionen: 2,
    tags: ["Pfanne", "Eier"],
    zutaten: ["150 g Vollkornmehl", "3 Eier", "300 ml Milch", "1 EL Rapsöl", "450 g TK-Blattspinat",
      "1 Zehe Knoblauch", "200 g Feta"],
    schritte: ["Mehl, Eier, Milch und eine Prise Salz zu einem glatten Teig verrühren, 10 Min quellen lassen.",
      "Spinat mit Knoblauch anbraten, Feta zerbröseln.",
      "Dünne Pfannkuchen backen, mit Spinat und Feta füllen."],
  },
  {
    id: "kohl-kartoffel-pfanne", name: "Kohl-Kartoffel-Pfanne mit Räuchertofu", minuten: 20, portionen: 2,
    tags: ["Pfanne"],
    zutaten: ["Beilage: Kartoffeln", "2 EL Rapsöl", "1 Zwiebeln", "½ Spitzkohl", "400 g Räuchertofu",
      "1 TL Kümmel"],
    schritte: ["Kartoffeln würfeln und in Öl ca. 10 Min braten.",
      "Zwiebel, Kohl in Streifen und gewürfelten Räuchertofu dazu, 10 Min mitbraten.",
      "Mit Kümmel (oder Paprikapulver), Salz und Pfeffer würzen."],
  },
  {
    id: "kichererbsen-bowl", name: "Bowl mit Ofen-Kichererbsen", minuten: 30, portionen: 2,
    tags: ["Ofen", "Reis"],
    zutaten: ["2 Dose Kichererbsen", "2 EL Rapsöl", "1 TL Paprikapulver", "Beilage: Reis", "¼ Rotkohl",
      "150 g Karotten", "½ Gurke", "200 g Naturjoghurt", "½ Zitrone"],
    schritte: ["Ofen auf 200 °C vorheizen, Reis kochen.",
      "Kichererbsen abtrocknen, mit Öl, Paprika und Salz 25 Min rösten.",
      "Rotkohl fein schneiden, Karotte reiben, Gurke würfeln.",
      "Joghurt mit Zitronensaft und Salz verrühren, alles in Schalen anrichten."],
  },
  {
    id: "minestrone", name: "Minestrone mit weißen Bohnen", minuten: 30, portionen: 2,
    tags: ["Suppe", "Pasta"],
    zutaten: ["1 Zwiebeln", "1 Stk Lauch", "200 g Karotten", "1 Zucchini", "1 EL Olivenöl",
      "1 Dose Stückige Tomaten", "2 TL Gemüsebrühe", "1 Dose Weiße Bohnen", "80 g Vollkornpenne", "30 g Parmesan"],
    schritte: ["Zwiebel, Lauch, Karotten und Zucchini klein schneiden und in Öl anbraten.",
      "Tomaten, 1 l Brühe und abgespülte Bohnen dazu, aufkochen.",
      "Nudeln dazu und 15 Min köcheln.",
      "Mit Parmesan servieren."],
  },
  {
    id: "brot-huettenkaese", name: "Vollkornbrot mit Hüttenkäse und Rohkost", minuten: 5, portionen: 1,
    tags: ["Schnell", "Kalt"],
    zutaten: ["200 g Hüttenkäse", "100 g Karotten", "½ Paprika"],
    schritte: ["2–3 Scheiben Vollkornbrot mit Hüttenkäse bestreichen.",
      "Karotten und Paprika in Sticks schneiden und dazu essen."],
  },
  {
    id: "ruehrei-gemuese", name: "Rührei mit Gemüse", minuten: 10, portionen: 1,
    tags: ["Schnell", "Pfanne", "Eier"],
    zutaten: ["3 Eier", "½ Paprika", "½ Zwiebeln", "1 TL Rapsöl"],
    schritte: ["Zwiebel und Paprika würfeln und in Öl anbraten.",
      "Eier verquirlen, salzen, dazugeben und bei mittlerer Hitze stocken lassen.",
      "Mit Brot essen."],
  },
];

// Die vier Wochen aus dem ursprünglichen Plan. Pro Tag [Mittag, Abend];
// "reste" heißt: Das Abendessen vom Vortag wird mit einer Portion mehr gekocht.
const PLAN_VORLAGEN = [
  { name: "Woche 1", tage: [
    ["brot-huettenkaese", "linsen-bolognese"], ["reste", "ofengemuese"], ["reste", "shakshuka"],
    ["couscous-salat", "tofu-pfanne"], ["reste", "bohnen-wraps"], ["reste", "linsen-kokos-curry"],
    ["reste", "kartoffel-linsen-suppe"]] },
  { name: "Woche 2", tage: [
    ["reste", "chili-sin-carne"], ["reste", "pasta-brokkoli-feta"], ["reste", "frittata"],
    ["reste", "kichererbsen-curry"], ["reste", "wrap-pizza"], ["reste", "linsen-eintopf"],
    ["reste", "gefuellte-paprika"]] },
  { name: "Woche 3", tage: [
    ["reste", "erdnuss-nudeln"], ["reste", "ofenkartoffeln"], ["reste", "linsen-dal"],
    ["reste", "gebratener-reis"], ["reste", "bohnen-bratlinge"], ["reste", "kuerbis-linsen-suppe"],
    ["reste", "nudelauflauf"]] },
  { name: "Woche 4", tage: [
    ["reste", "mex-reispfanne"], ["reste", "kichererbsen-pfanne"], ["reste", "spinat-feta-pfannkuchen"],
    ["reste", "kohl-kartoffel-pfanne"], ["reste", "linsen-bolognese"], ["reste", "kichererbsen-bowl"],
    ["reste", "minestrone"]] },
];

const SPORT_TIPPS = [
  "2–3 Stunden vor dem Training eine normale Mahlzeit, meist das Mittagessen.",
  "Knapp vorher bei Hunger: Banane oder Brot mit Honig.",
  "Danach: Abendessen mit etwas mehr Reis, Nudeln, Kartoffeln oder Brot.",
  "Später bei Hunger: Quark oder Skyr mit Obst.",
  "Mehr trinken als an anderen Tagen.",
];

const STANDARD_EINSTELLUNGEN = {
  fruehstueck: "Overnight Oats oder Quark mit Haferflocken, Obst, Leinsamen und Walnüssen – " +
    "alternativ Vollkornbrot mit Ei oder Kräuterquark und Rohkost.",
  // Mengen für einen typischen Tag – zählen in die Tagessumme und (× 7) in die Einkaufsliste.
  fruehstueckZutaten: ["80 g Haferflocken", "200 ml Milch", "140 g Skyr", "1 Apfel", "10 g Leinsamen", "15 g Walnüsse"],
  snack: ["250 g Magerquark", "1 Banane"], // täglicher Eiweiß-Snack
  training: ["1 Banane"],                  // vor dem Training, nur an Sporttagen
  sporttage: [0, 2, 4], // Mo, Mi, Fr (0 = Montag)
  einkaufstag: 0, // Großeinkauf für die Woche (0 = Montag, 5 = Samstag vor der Woche)
  // Beilagen pro Portion (roh). Rezepte mit "Beilage: Reis" usw. nehmen diese Mengen.
  beilagen: { nudeln: 150, reis: 120, couscous: 120, kartoffeln: 500, sportZuschlag: 25 },
  // Tagesziel, grob geschätzt für einen aktiven Mann Anfang 20 mit Kraftsport
  ziele: { kcal: [2600, 3000], eiweiss: [100, 120] },
  // Was sonst jede Woche gekauft wird (gleiches Format wie Rezeptzutaten).
  basics: [
    "1 Stk Vollkornbrot",
    "6 Eier",
    "500 g Naturjoghurt",
    "500 g Karotten",
    "1 Gurke",
  ],
  kurzbefehl: "Einkauf importieren",
};

// Frühere Standard-Basics – wer sie nie geändert hat, bekommt beim Update die neuen
const ALTE_STANDARD_BASICS = [
  "1 Stk Vollkornbrot", "6 Eier", "500 g Magerquark", "500 g Skyr", "500 g Naturjoghurt",
  "1 l Milch", "1 kg Äpfel", "6 Bananen", "500 g Karotten",
];
